# Generated by Django 6.0.4 on 2026-06-01 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='스터디룸 이름')),
                ('building', models.CharField(max_length=50, verbose_name='건물')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='층')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='좌석 수')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 가능')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['building', 'floor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=20, verbose_name='좌석 번호')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 가능')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='rooms.studyroom', verbose_name='스터디룸')),
            ],
            options={
                'ordering': ['room', 'seat_number'],
                'unique_together': {('room', 'seat_number')},
            },
        ),
    ]
